config/routes.rb
Rails.application.routes.draw do

  root 'user_events#index'
 
  resources :users 
  resources :admins do
  collection do
      get 'download_pdf'
    end
  end
  resources :user_events
  resources :password_resets
  resources :sessions, only: [:new, :create, :destroy]
  resources :user_lists
  
  match '/events',  to: 'user_events#index',   via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :payments
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  validates :birthdate, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, on: :create
  
  mount_uploader :avatar, AvatarUploader 
  self.per_page = 10
  
  default_scope{order('first_name, last_name desc')}
  scope :find_by_birth_month, ->(month){where('MONTH(birthdate) = ?', month) if month.present?}
  scope :search, ->(search){where('first_name like ? or last_name like ?', "#{search}", "#{search}") if search.present? && search.length > 0}

  
  def send_password_reset
    self.password_resets_token = User.new_token
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver_now
  end
  
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_token)
    end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_filter :signed_in_user, :admin_user
  
  def download_pdf
    list = UsersListPDF.new
    list.table_headers = User.find_by_birth_month Date.today.month
    output = list.to_pdf User.all
    send_data output, :type => 'application/pdf', :filename => "users.pdf"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  def signed_in_user
      store_location
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
  end
  
  def correct_user
      @user = User.find(params[:id])
      redirect_to(signin_url) unless current_user?(@user)
    end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by_email(params[:email]);
    @user.send_password_reset if @user
    flash[:success] = "Email sent with password reset instructions."
    redirect_to root_path
  end
  
  def edit
    @user = User.find_by_password_resets_token(params[:id])
  end
  
  def update
    @user = User.find_by_password_resets_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      flash[:success] = "Password reset has expired."
      redirect_to new_password_reset_path
    elsif @user.update_attributes(params[:user])
      flash[:success] = "Password has been reset!"
      redirect_to root_url 
    else
      render :edit
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email params[:session][:email].downcase
    if user && user.authenticate(params[:session][:password]) 
      sign_in user
      redirect_back_or root_path
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    sign_out
    redirect_to signin_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/user_events_controller.rb
class UserEventsController < ApplicationController
  def index
    @date =  params[:month] ? Date.parse(params[:month]) : Date.today
    @users = event_users(@date.month, @date.year)
    respond_to do |format|
      format.html
      format.js
      format.json {render json: @users}
    end
  end
  
  private
    def event_users(month, year)
      User.select(:id, :first_name, :last_name, :avatar,
        "STR_TO_DATE(CONCAT(DAY(birthdate), ' #{month} #{year}'),'%d %m %Y') as this_year_birthdate")
      .find_by_birth_month(month)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update, :index, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  
  def index
    @users = User.search(params[:search]).paginate(:page => params[:page])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @user = User.new()
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.welcome_email(@user).deliver_later
      flash[:success] = "Welcome to the Sample App!"
      sign_in @user
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    attributes = user_params;
    attributes[:avatar] = params[:user][:avatar]
    if @user.update_attributes(attributes)
      flash[:success] = "Profile updated"
      render 'edit'
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    respond_to do |format|
      format.html { redirect_to users_url }
      format.js
    end
  end
  
  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :birthdate,
        :password, :password_confirmation)
    end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def is_admin?
    current_user.admin?
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  
  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def change_year(year, date)
    Date.new(date).change(year: year)
  end
end

app/views/admins/index.html.erb
<div>
</div>

app/views/layouts/_debug.erb
<%= debug(params) %>
<%= debug(@debug_out) %>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class ="container">
      <%= image_tag("Light-IT.png", :alt => "Light IT", :class => "img-responsive") %>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-custom navbar-fixed-top">
    <div class="container">
      <div class = ""></div>
      <ul class="nav pull-right">
        <li><%= link_to "Home", root_path %></li>
        <% if signed_in? %>
          <% if is_admin? %>
            <li><%= link_to "Users PDF", download_pdf_admins_path %></li>
          <% end %>
          <li><%= link_to "Users", users_path %></li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign out", signout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Birthdays</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container master-container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
<%= render 'layouts/debug' if Rails.env.development? %>
</body>
</html>

app/views/password_resets/edit.html.erb
<h1>Sign in</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @user, :url => password_reset_path(params[:id]), :html => {:class => "form-control"} do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :password %>
      <%= f.password_field :password %>
      
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
      
      <div><%= f.submit "Update Password", class: "btn btn-custom" %></div>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<h1>Reset password</h1>

<div class="row">
  <div class="span6 offset3 text-center">
    <%= form_tag password_resets_path, :method => 'post', :html => {:class => "form-control"} do |f| %>
      <div class="form-group">

        <%= label :email, 'Email' %>
        <%= text_field :email, params[:email] %>
          
        <div><%= submit_tag "Reset", class: "btn btn-custom" %></div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<%= "home.html" %>

app/views/user_events/_calendar.html.erb
<h1 id="month" class = "month">
  <%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m-%d"), remote: true %>
    <%=h @date.strftime("%B %Y") %>
  <%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m-%d"), remote: true %>
</h1>
<%= calendar_for(@users , :year => @date.year, :month => @date.month, :first_day_of_week => 1) do |t| %>
  <%= t.head('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun') %>
  <%= t.day(:day_method => :this_year_birthdate) do |day, tasks| %> 
    <%= day.day %>
    <% tasks.each do |task| %>
      <%= h(link_to "#{task.first_name} #{task.last_name}", task) %>
    <% end %>
  <% end %>
<% end %>

app/views/user_events/index.html.erb
<div id = "calendar" class="calendar">
  <%= render 'calendar' %>
</div>

app/views/user_events/index.js.erb
$('a[data-remote]').on('ajax:success', function(xhr, status, error) {
  $('#calendar').html("<%= escape_javascript(render 'calendar')%>");
});

app/views/users/_user.html.erb
<li>
  <%= link_to "#{user.first_name} #{user.last_name}", user %> 
  <%= user.birthdate %>
  <% if is_admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete, remote: true,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/destroy.js.erb
$('a[data-remote]').on('ajax:success', function(xhr, status, error) {
  $(this).parent('li').remove();
});

app/views/users/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3 text-center">
    <%= simple_form_for @user, :html => {multipart: true , class:  'form-control' } do |f| %>

        <%= f.error_notification %>
       
        <%= f.input :first_name %>
       
        <%= f.input :last_name %>
      
        <%= f.date_select :birthdate, {:prompt => { :day => 'Day', :month => 'Month', :year => 'Year' }, :start_year => 1960, :end_year => Date.today.year},  {:class => 'span2'} %>
     
        <%= f.input :email %>

        <%= image_tag(@user.avatar_url) if @user.avatar? %>
        <%= f.file_field :avatar %>
        <%= f.hidden_field :avatar_cache %>

        <div><%= f.submit "Save changes", class: "btn btn-custom" %></div>

    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users:</h1>
<%= form_tag users_path, :method => 'get', remote: true, class: "form-inline" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", class: "btn btn-custom" %>
  </p>
<% end %>
  
<%= table_for(@users, :html => {:class => 'table table-hover'}) do |t| %>
  <%= t.head do %>
    <%= t.r do %>
      <%= t.h('Name') %>
      <%= t.h('Birthday') %>
      <%= t.h('Delete') if current_user.admin? %>
    <% end %>
  <% end %>
  <%= t.body do |user| %>
    <%= t.r do %>
      <%= t.d(link_to "#{user.first_name} #{user.last_name}", user) %>
      <%= t.d(h(user.birthdate)) %>
      <% if current_user.admin? && !current_user?(user) %>
        <%= t.d(link_to "delete", user, method: :delete, remote: true, data: { confirm: "You sure?" })%>
      <% end %>  
    <% end %>
  <% end %>
<% end %>
<%= will_paginate%>

app/views/users/index.js.erb
$('form[data-remote]').on('ajax:success', function(xhr, status, error) {
  $('#users').html("<%= escape_javascript(render @users)%>");
});

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3 text-center">
    <%= simple_form_for @user, :html => {:class => "form-control"} do |f| %>
      <div class="form-group">
        <%= f.error_notification %>

        <%= f.input :first_name %>

        <%= f.input :last_name %>

        <%= f.input :email %>

        <%= f.date_select :birthdate, {:prompt => { :day => 'Day', :month => 'Month', :year => 'Year' }, :start_year => 1960},  {:class => 'span2'} %>

        <%= f.input :password %>

        <%= f.input :password_confirmation %>

        <div><%= f.submit "Create my account", class: "btn btn-custom" %></div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="span6 offset3 text-center">
      <h1><%="#{@user.first_name} #{@user.last_name}"%></h1>
      <h2><%=@user.birthdate.strftime('%d.%m.%Y')%></h2>
      <div class="span4 offset1"><%= image_tag(@user.avatar_url ? @user.avatar_url : 'no-image.jpg') %></div>
  </div>
</div>